version: '3.8'
services:
    app:
        build: .
        container_name: simpletasks-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
    db:
        image: mysql:8.0
        container_name: simpletasks-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: simpletasks
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
    nginx:
        image: nginx:alpine
        container_name: simpletasks-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
